#pragma once

#include "common/Types.h"
#include "core/Config.h"
#include <memory>
#include <vector>
#include <unordered_map>

namespace minesim {

class BranchPredictor {
public:
    BranchPredictor() = default;
    virtual ~BranchPredictor() = default;

    // Factory method
    static std::unique_ptr<BranchPredictor> create(const MicroArchConfig& config);

    // Direction prediction (conditional branches)
    virtual bool predict(Addr pc) = 0;
    virtual void update(Addr pc, bool actual_taken) = 0;

    // Whether this predictor is oracle (no mispredict penalty should apply).
    virtual bool is_perfect() const { return false; }

    // Indirect target prediction (BTB).
    // Returns true on correct target, false on mispredict (and updates stats).
    bool predict_indirect(Addr pc, Addr actual_target);

    // Direct taken branches (taken conditional/direct call/direct jump) also
    // consult a BTB, but the structure is larger and less alias-prone than the
    // indirect target array. Modeling them separately avoids charging every
    // taken direct branch as an "indirect" miss.
    bool predict_direct(Addr pc, Addr actual_target);

    // Return address prediction (RSB).
    // Returns true if RSB top matches actual_target, false otherwise (and updates stats).
    bool predict_return(Addr actual_target);

    // Push the (computed) return target when a call is encountered.
    void push_call(Addr return_target);

    // Statistics
    struct Stats {
        uint64_t predictions = 0;
        uint64_t correct_predictions = 0;
        uint64_t mispredictions = 0;

        // Sub-categories
        uint64_t cond_predictions = 0;
        uint64_t cond_mispredictions = 0;

        uint64_t direct_predictions = 0;
        uint64_t direct_mispredictions = 0;

        uint64_t indirect_predictions = 0;
        uint64_t indirect_mispredictions = 0;

        uint64_t return_predictions = 0;
        uint64_t return_mispredictions = 0;
    };

    const Stats& get_stats() const { return stats_; }
    void reset_stats();
    virtual void print_stats() const;

    // Aggregate mispredictions across cond / indirect / return.
    uint64_t total_mispredictions() const {
        return stats_.cond_mispredictions + stats_.direct_mispredictions +
               stats_.indirect_mispredictions + stats_.return_mispredictions;
    }

protected:
    Stats stats_;

    struct BTBEntry {
        Addr tag = 0;
        Addr target = 0;
        uint64_t last_used = 0;
        bool valid = false;
    };

    // Keep the direct-target BTB at the same total entry count as before, but
    // make it set-associative. The previous direct-mapped table massively
    // overstated target misses once every taken direct branch started probing
    // the BTB.
    static constexpr size_t kDirectBTBSets = 1024;
    static constexpr size_t kDirectBTBWays = 4;
    std::vector<BTBEntry> direct_btb_{kDirectBTBSets * kDirectBTBWays};

    // Indirect targets remain more difficult and can use a smaller direct-
    // mapped structure without dominating branch.misses.
    static constexpr size_t kIndirectBTBSize = 512;
    std::vector<BTBEntry> indirect_btb_{kIndirectBTBSize};
    uint64_t btb_use_clock_ = 1;

    // RSB: SPR has ~16-entry RAS. A too-large RSB hides return mispredicts
    // generated by deep callstacks / longjmp-style unwinds.
    static constexpr size_t kRSBSize = 16;
    std::vector<Addr> rsb_;
};

class OneBitBranchPredictor : public BranchPredictor {
public:
    OneBitBranchPredictor(uint32_t size);

    bool predict(Addr pc) override;
    void update(Addr pc, bool actual_taken) override;

private:
    std::vector<bool> table_;
};

class BimodalBranchPredictor : public BranchPredictor {
public:
    BimodalBranchPredictor(uint32_t size);

    bool predict(Addr pc) override;
    void update(Addr pc, bool actual_taken) override;

private:
    std::vector<uint8_t> table_; // 2-bit saturating counters (0-3)
};

// GShare: PHT indexed by (pc XOR global-history-register). The GHR captures
// recent control-flow context, which causes table aliasing on workloads with
// many distinct branches sharing similar PCs (which is what happens to a
// bimodal table that is too small to cover the working set of static
// branches). This reproduces the misprediction floor that perf observes
// (~12 mispredicts per 1M branches on analytics-style loops -> bimodal-4K
// reports ~70 mispredicts/1M, gshare reports closer to the real machine).
class GShareBranchPredictor : public BranchPredictor {
public:
    GShareBranchPredictor(uint32_t size, uint32_t history_bits);

    bool predict(Addr pc) override;
    void update(Addr pc, bool actual_taken) override;

private:
    uint32_t index_for(Addr pc) const;

    std::vector<uint8_t> table_;     // 2-bit saturating counters
    uint32_t history_bits_;
    uint64_t ghr_;                   // global history register (1 = taken)
    uint64_t ghr_mask_;
    uint32_t table_mask_;
};

// Sniper/Pentium-M inspired hybrid predictor:
// tagged global predictor first, loop predictor second, bimodal fallback last.
class HybridBranchPredictor : public BranchPredictor {
public:
    HybridBranchPredictor(uint32_t size, uint32_t history_bits);

    bool predict(Addr pc) override;
    void update(Addr pc, bool actual_taken) override;
    void print_stats() const override;

private:
    struct GlobalEntry {
        uint16_t tag = 0;
        uint8_t counter = 1;
        uint64_t last_used = 0;
        bool valid = false;
    };

    struct LoopEntry {
        Addr tag = 0;
        uint32_t run_length = 0;
        uint32_t stable_length = 0;
        uint8_t confidence = 0;
        uint64_t last_used = 0;
        bool last_actual = false;
        bool valid = false;
    };

    uint32_t global_index(Addr pc) const;
    uint16_t global_tag(Addr pc) const;
    bool global_lookup(Addr pc, bool& prediction, size_t& way_index) const;
    void global_update(Addr pc, bool actual_taken, bool allocate);
    void global_evict(Addr pc);

    bool loop_lookup(Addr pc, bool& prediction, size_t& way_index) const;
    void loop_update(Addr pc, bool actual_taken);

    uint32_t bimodal_index(Addr pc) const;
    bool bimodal_predict(Addr pc) const;
    void bimodal_update(Addr pc, bool actual_taken);

    uint32_t gshare_index(Addr pc) const;
    bool gshare_predict(Addr pc) const;
    void gshare_update(Addr pc, bool actual_taken);

    void update_history(bool actual_taken);

    std::vector<uint8_t> bimodal_table_;
    uint32_t bimodal_mask_;
    std::vector<uint8_t> gshare_table_;
    uint32_t gshare_mask_;
    std::vector<uint8_t> chooser_table_;  // 2-bit: >=2 use gshare, <2 use bimodal

    static constexpr size_t kGlobalWays = 4;
    std::vector<GlobalEntry> global_table_;
    uint32_t global_sets_;
    uint32_t global_mask_;
    uint32_t history_bits_;
    uint64_t ghr_;
    uint64_t ghr_mask_;
    uint64_t global_use_clock_ = 1;

    static constexpr size_t kLoopSets = 1024;
    static constexpr size_t kLoopWays = 4;
    std::vector<LoopEntry> loop_table_;
    uint64_t loop_use_clock_ = 1;

    bool last_global_hit_ = false;
    bool last_loop_hit_ = false;
    bool last_bimodal_pred_ = false;
    bool last_gshare_pred_ = false;
    bool last_prediction_ = false;
    bool last_global_pred_ = false;
    bool last_loop_pred_ = false;
    bool last_chooser_pred_ = false;
    bool last_use_gshare_ = false;
    bool last_global_differs_from_chooser_ = false;

    // Internal component-level statistics (observation-only, no logic change).
    struct InternalStats {
        uint64_t global_hits = 0;
        uint64_t global_misses = 0;
        uint64_t loop_hits = 0;
        uint64_t loop_misses = 0;
        uint64_t chooser_use_gshare = 0;
        uint64_t chooser_use_bimodal = 0;
        uint64_t bimodal_correct_only = 0;   // bimodal correct, gshare wrong
        uint64_t gshare_correct_only = 0;    // gshare correct, bimodal wrong
        uint64_t both_wrong = 0;             // both bimodal and gshare wrong
        uint64_t global_loop_override = 0;   // global+loop agree, override chooser
        uint64_t global_correct_only = 0;    // global hit, global correct, final wrong
        uint64_t global_wrong_but_chooser_correct = 0; // global hit, global wrong, chooser correct
        uint64_t global_hit_differs_from_chooser = 0; // global hit and global != chooser
        uint64_t global_hit_differs_and_global_correct = 0; // above + global correct
        uint64_t loop_correct_only = 0;      // loop hit, loop correct, final wrong
        uint64_t loop_hit_and_correct = 0;   // loop hit and loop correct
        uint64_t final_from_chooser_bimodal = 0;
        uint64_t final_from_chooser_gshare = 0;
        uint64_t final_from_global_loop_override = 0;
    } istats_;

    // Per-PC both_wrong attribution (observation-only).
    std::unordered_map<Addr, uint64_t> both_wrong_per_pc_;
    std::unordered_map<Addr, uint64_t> cond_pred_per_pc_;

    // Per-PC pattern analysis (observation-only).
    struct PerPCPattern {
        uint64_t dynamic_count = 0;
        uint64_t both_wrong_count = 0;
        uint64_t taken_count = 0;
        uint64_t flip_count = 0;
        uint64_t tt = 0, tn = 0, nt = 0, nn = 0;
        uint64_t max_run_t = 0, max_run_n = 0;
        uint64_t cur_run_t = 0, cur_run_n = 0;
        bool last_actual = false;
        bool has_last = false;
        uint64_t local_1bit_correct = 0;
        uint8_t local_2bit_counter = 1;
        uint64_t local_2bit_correct = 0;
        uint64_t bimodal_correct = 0;
        uint64_t gshare_correct = 0;
        uint64_t global_hit_count = 0;
        uint64_t global_correct = 0;
        uint64_t global_hit_differs_chooser = 0;
        uint64_t global_hit_differs_correct = 0;
    };
    std::unordered_map<Addr, PerPCPattern> pc_patterns_;
};

class PerfectBranchPredictor : public BranchPredictor {
public:
    bool predict(Addr pc) override { (void)pc; return false; /* Actual doesn't matter for perfect, we just override logic later */ }
    void update(Addr pc, bool actual_taken) override {
        (void)pc; (void)actual_taken;
        stats_.predictions++;
        stats_.correct_predictions++;
        stats_.cond_predictions++;
    }
    bool is_perfect() const override { return true; }
};

} // namespace minesim
